name: TantheMan
favicon: null
layout_spectrum: 0
typography_spectrum: 0.0998
title: Tan the Man
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fef4eb'
    - '#231f1e'
    - '#acb8b6'
    - '#a88170'
    - '#e1b650'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
