name: TantheMan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0998
title: Tan the Man
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8aaca7'
    - '#447780'
    - '#ddad91'
    - '#3a3e55'
    - '#ffd1aa'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
